/**
  ******************************************************************************
  * @file    mx.c
  * @author  SRA - GPM
  *
  *
  *
  * @brief Project peripherals configuration files.
  *
  * This files defines the peripherals configuration parameters that can be used
  * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
  * between the initialization code generated by CubeMX (see the .ioc file
  * in the tools folder) and the eLooM framework.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

#include "mx.h"
#include "tim.h"
#include "i3c.h"
#include "spi.h"
#include "gpio.h"
#include "gpdma.h"
#include "usb.h"


/**
  * TIM7 initialization parameters.
  */
const MX_TIMParams_t MX_TIM7InitParams =
{
  .p_mx_init_f = MX_TIM7_Init,
  .p_tim = &htim7,
  .irq_n = TIM7_IRQn
};

/**
  * I3C1 initialization parameters.
  */
const MX_I3CParams_t MX_I3C1InitParams =
{
  .p_mx_init_f = MX_I3C1_Init,
  .p_i3c_handle = &hi3c1,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i3c_er_irq_n = I3C1_ER_IRQn,
  .i3c_ev_irq_n = I3C1_EV_IRQn,
  .i3c_dma_tc_irq_n = GPDMA1_Channel0_IRQn,
  .i3c_dma_rx_irq_n = GPDMA1_Channel2_IRQn,
  .i3c_dma_tx_irq_n = GPDMA1_Channel1_IRQn
};

/**
  * SPI1 initialization parameters.
  */
const MX_SPIParams_t MX_SPI1InitParams =
{
  .p_mx_init_f = MX_SPI1_Init,
  .p_spi_handle = &hspi1,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .spi_irq_n = SPI1_IRQn,
  .spi_dma_rx_irq_n = GPDMA1_Channel4_IRQn,
  .spi_dma_tx_irq_n = GPDMA1_Channel5_IRQn
};

/**
  * LED Red Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LEDRedInitParams =
{
  MX_GPIO_PG4_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_RED_Pin,
  LED_RED_GPIO_Port
};

/**
  * LED Green Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LEDGreenInitParams =
{
  MX_GPIO_PB0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_GREEN_Pin,
  LED_GREEN_GPIO_Port
};

/**
  * LED Blue Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LEDYellowInitParams =
{
  MX_GPIO_PF4_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_YELLOW_Pin,
  LED_YELLOW_GPIO_Port
};

/**
  * (IIS2DULPX_INT1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_IIS2DULPX_INT1InitParams =
{
  MX_GPIO_PC3_Init,
  IIS2DULPX_INT1_EXTI_IRQn,
  IIS2DULPX_INT1_Pin,
  IIS2DULPX_INT1_GPIO_Port
};

/**
  * (IIS2MDC_DRDY) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_IIS2MDC_DRDYInitParams =
{
  MX_GPIO_PB1_Init,
  IIS2MDC_DRDY_EXTI_IRQn,
  IIS2MDC_DRDY_Pin,
  IIS2MDC_DRDY_GPIO_Port
};

/**
  * (ISM330IS_INT2) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_ISM330IS_INT2InitParams =
{
  MX_GPIO_PG12_Init,
  ISM330IS_INT2_EXTI_IRQn,
  ISM330IS_INT2_Pin,
  ISM330IS_INT2_GPIO_Port
};

/**
  * (ISM6HG256X_INT1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_ISM6HG256X_INT1InitParams =
{
  MX_GPIO_PE11_Init,
  ISM6HG256X_INT1_EXTI_IRQn,
  ISM6HG256X_INT1_Pin,
  ISM6HG256X_INT1_GPIO_Port
};

/**
  * (ISM6HG256X_INT2) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_ISM6HG256X_INT2InitParams =
{
  MX_GPIO_PE14_Init,
  ISM6HG256X_INT2_EXTI_IRQn,
  ISM6HG256X_INT2_Pin,
  ISM6HG256X_INT2_GPIO_Port
};

/**
  * (SPI_CS) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_EXTERNALInitParams =
{
  MX_GPIO_PD14_Init,
  UsageFault_IRQn, /*!< NOT USED */
  SPI_CS_Pin,
  SPI_CS_GPIO_Port
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_DRD_FS,
  .p_mx_init_f = MX_USB_PCD_Init,
  .irq_n = USB_DRD_FS_IRQn
};

